import { Row, Col, Typography, Card } from 'antd';
import styled from '@emotion/styled';
import { keyframes } from '@emotion/react';
import { 
  RobotOutlined, 
  ApiOutlined, 
  CloudServerOutlined, 
  LineChartOutlined,
  DatabaseOutlined,
  SecurityScanOutlined,
  TeamOutlined,
  CodeSandboxOutlined
} from '@ant-design/icons';

const { Title, Paragraph } = Typography;

const fadeIn = keyframes`
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
`;

const Section = styled.section`
  padding: 100px 0;
  background: linear-gradient(180deg, #f9fbfd 0%, #ffffff 100%);
  position: relative;
  overflow: hidden;
`;

const Container = styled.div`
  position: relative;
  z-index: 1;
`;

const SectionTitle = styled(Title)`
  text-align: center;
  margin-bottom: 16px !important;
  font-size: 2.5rem !important;
  background: linear-gradient(90deg, #1890ff 0%, #36cfc9 100%);
  -webkit-background-clip: text;
  background-clip: text;
  -webkit-text-fill-color: transparent;
  display: inline-block;
  margin: 0 auto 16px !important;
  opacity: 0;
  animation: ${fadeIn} 0.6s ease-out 0.2s forwards;
  
  @media (max-width: 768px) {
    font-size: 2rem !important;
  }
`;

const SectionSubtitle = styled(Paragraph)`
  text-align: center;
  max-width: 700px;
  margin: 0 auto 64px !important;
  font-size: 1.1rem;
  color: #666;
  line-height: 1.6;
  opacity: 0;
  animation: ${fadeIn} 0.6s ease-out 0.3s forwards;
`;

const FeatureCard = styled(Card)`
  height: 100%;
  border-radius: 16px;
  transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
  border: 1px solid rgba(24, 144, 255, 0.1);
  background: rgba(255, 255, 255, 0.7);
  backdrop-filter: blur(10px);
  overflow: hidden;
  position: relative;
  z-index: 1;
  
  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 4px;
    background: linear-gradient(90deg, #1890ff 0%, #36cfc9 100%);
    transform: scaleX(0);
    transform-origin: left;
    transition: transform 0.4s ease;
  }
  
  .ant-card-body {
    padding: 32px 24px;
    position: relative;
    z-index: 2;
  }
  
  &:hover {
    transform: translateY(-8px) scale(1.02);
    box-shadow: 0 20px 40px rgba(24, 144, 255, 0.1);
    border-color: rgba(24, 144, 255, 0.2);
    
    &::before {
      transform: scaleX(1);
    }
    
    .feature-icon {
      transform: scale(1.1) rotate(5deg);
      background: linear-gradient(135deg, #1890ff 0%, #36cfc9 100%);
      -webkit-background-clip: text;
      background-clip: text;
      -webkit-text-fill-color: transparent;
    }
  }
`;

const IconWrapper = styled.div`
  width: 70px;
  height: 70px;
  border-radius: 50%;
  background: linear-gradient(135deg, rgba(24, 144, 255, 0.1) 0%, rgba(54, 207, 201, 0.1) 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 24px;
  transition: all 0.4s ease;
  
  .feature-icon {
    font-size: 32px;
    color: #1890ff;
    transition: all 0.4s ease;
  }
`;

const FeatureTitle = styled(Title)`
  font-size: 1.4rem !important;
  margin-bottom: 16px !important;
  color: #2c3e50 !important;
  text-align: center;
  font-weight: 700 !important;
`;

const FeatureDescription = styled(Paragraph)`
  color: #666 !important;
  text-align: center;
  margin-bottom: 0 !important;
  font-size: 1rem;
  line-height: 1.7;
`;

const features = [
  {
    icon: <RobotOutlined className="feature-icon" />,
    title: 'AI Teacher',
    description: 'This fully automated AI tutor allows you to practice speaking, improve your grammar, and expand your vocabulary in a foreign language. It never gets tired, bored, or impatient – always ready to support your learning.'
  },
  {
    icon: <CodeSandboxOutlined className="feature-icon" />,
    title: 'Essay AI Checking',
    description: 'Written an assignment in a foreign language but have no way to evaluate it? With our platform, just submit your text and get instant feedback and scoring – no teacher required.'
  },
  {
    icon: <SecurityScanOutlined className="feature-icon" />,
    title: 'AI Detector',
    description: 'Now it’s no longer a challenge to determine whether your student’s writing was generated by AI or written by themselves – simply submit the text and get the result instantly.'
  }
];

export default function FeaturesSection() {
  return (
    <Section id="features">
      <Container className="container">
        <SectionTitle level={2}>Our Skills</SectionTitle>
        <SectionSubtitle>
          We have developed a comprehensive set of tools to create a reliable and interactive learning experience. Our key features include:
        </SectionSubtitle>
        <Row gutter={[24, 32]}>
          {features.map((feature, index) => (
            <Col 
              key={index} 
              xs={24} 
              sm={12} 
              lg={6}
              style={{
                opacity: 0,
                animation: `${fadeIn} 0.6s ease-out ${0.4 + (index * 0.1)}s forwards`
              }}
            >
              <FeatureCard>
                <IconWrapper>
                  {feature.icon}
                </IconWrapper>
                <FeatureTitle level={3}>{feature.title}</FeatureTitle>
                <FeatureDescription>
                  {feature.description}
                </FeatureDescription>
              </FeatureCard>
            </Col>
          ))}
        </Row>
      </Container>
    </Section>
  );
}
