import { useState } from 'react';
import { Row, Col, Typography } from 'antd';
import styled from '@emotion/styled';
import ProjectCard from './ProjectCard';
import EssayCheckerModal from './demos/EssayCheckerModal';
import AIDetectorModal from './demos/AIDetectorModal';
import { Project } from '@/types/project';

const { Title, Paragraph } = Typography;

const Section = styled.section`
  padding: 80px 0;
  background: #fff;
`;

const SectionTitle = styled(Title)`
  text-align: center !important;
  margin-bottom: 16px !important;
`;

const SectionSubtitle = styled(Paragraph)`
  text-align: center !important;
  max-width: 800px;
  margin: 0 auto 60px !important;
`;

const ProjectsGrid = styled(Row)`
  margin: 0 -12px;
  .ant-col {
    padding: 12px;
  }
`;

const staticProjects: Project[] = [
  {
    id: 'essay-demo',
    title: 'Essay Checking',
    description: 'Check your IELTS-style essay and instantly receive band score feedback and detailed suggestions.',
    imageUrl: '/images/projects/essay-checking.png',
    tags: ['IELTS', 'Writing', 'Feedback'],
    category: 'NLP',
    demoUrl: '#',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ai-detector-demo',
    title: 'AI Detector',
    description: 'Detect whether a text was written by a human or generated by AI with percentage breakdown.',
    imageUrl: '/images/projects/ai-detector.png',
    tags: ['Detection', 'AI', 'NLP'],
    category: 'NLP',
    demoUrl: '#',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export default function ProjectsSection() {
  const [essayModalOpen, setEssayModalOpen] = useState(false);
  const [aiModalOpen, setAiModalOpen] = useState(false);

  const handleView = (project: Project) => {
    const lower = project.title.toLowerCase();
    if (lower.includes('essay')) {
      setEssayModalOpen(true);
    } else if (lower.includes('detector') || lower.includes('detect')) {
      setAiModalOpen(true);
    }
  };

  return (
    <>
      <Section id="projects">
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 24px' }}>
          <SectionTitle level={2}>Our AI Projects</SectionTitle>
          <SectionSubtitle>
            Explore our interactive AI demos below.
          </SectionSubtitle>
          <ProjectsGrid gutter={[24, 32]}>
            {staticProjects.map((project) => (
              <Col key={project.id} xs={24} sm={12} lg={8}>
                <ProjectCard project={project} onView={handleView} />
              </Col>
            ))}
          </ProjectsGrid>
        </div>
      </Section>
      <EssayCheckerModal open={essayModalOpen} onClose={() => setEssayModalOpen(false)} />
      <AIDetectorModal open={aiModalOpen} onClose={() => setAiModalOpen(false)} />
    </>
  );
}
