'use client';

import { Typography } from 'antd';
import styled from '@emotion/styled';
import { keyframes } from '@emotion/react';

const { Title, Paragraph } = Typography;

const fadeIn = keyframes`
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
`;

const AboutContainer = styled.section`
  padding: 80px 0;
  background-color: #fff;
`;

const ContentWrapper = styled.div`
  max-width: 900px;
  margin: 0 auto;
  text-align: center;
  padding: 0 24px;
`;

const StyledTitle = styled(Title)`
  font-size: 2.8rem !important;
  margin-bottom: 24px !important;
  animation: ${fadeIn} 0.8s ease-out forwards;
  opacity: 0;
  animation-delay: 0.2s;
  position: relative;
  display: inline-block;

  &::after {
    content: '';
    position: absolute;
    left: 50%;
    bottom: -10px;
    transform: translateX(-50%);
    width: 60px;
    height: 4px;
    background: linear-gradient(90deg, #1890ff 0%, #36cfc9 100%);
    border-radius: 2px;
  }
`;

const StyledParagraph = styled(Paragraph)`
  font-size: 1.1rem;
  color: #595959;
  animation: ${fadeIn} 0.8s ease-out forwards;
  opacity: 0;
  animation-delay: 0.4s;
  line-height: 1.8;
`;

export default function AboutSection() {
  return (
    <AboutContainer id="about">
      <ContentWrapper>
        <StyledTitle level={2}>About Us</StyledTitle>
        <StyledParagraph style={{ marginTop: '30px' }}>
          We have developed an AI-powered learning platform designed to support those who struggle with learning foreign languages. The platform enables users to have conversations in English with the help of artificial intelligence and receive instant feedback on their essays through automatic scoring. For teachers, it includes an AI detection feature that can identify whether a text was written by a human or generated by AI. This system makes self-education more interactive, personalized, and reliable.
        </StyledParagraph>
      </ContentWrapper>
    </AboutContainer>
  );
}
